#include "rmt/io/mesh/export/ObjWriter.h"

#include <fstream>

#include "rmt/io/mesh/export/MeshExporter.h"

namespace rmt {

bool MeshExporter::writeOBJFile(const Mesh& mesh, const std::string& filename) {
    log("💾 Writing OBJ file: " + filename, 0);

    std::ofstream file(filename);
    if (!file.is_open()) {
        log("❌ Could not open file for writing: " + filename, 2);
        log("   Check if the directory exists and you have write permissions.", 2);
        return false;
    }

    file << "# OBJ file generated by RayMarching Tool\n";
    file << "# Generated on: " << __DATE__ << " " << __TIME__ << "\n";
    file << "# Vertices: " << mesh.vertices.size() << "\n";
    file << "# Triangles: " << mesh.triangles.size() << "\n";
    file << "# \n";
    file << "# This mesh was generated using the Marching Cubes algorithm\n";
    file << "# from Signed Distance Field (SDF) data\n\n";

    for (const Vertex& v : mesh.vertices) {
        file << "v " << v.x << " " << v.y << " " << v.z << "\n";
    }

    file << "\n# Faces (triangles)\n";

    for (const Triangle& t : mesh.triangles) {
        file << "f " << (t.v1 + 1) << " " << (t.v2 + 1) << " " << (t.v3 + 1) << "\n";
    }

    file.close();

    std::ifstream checkFile(filename);
    if (!checkFile.is_open()) {
        log("❌ Failed to verify exported file!", 2);
        return false;
    }
    checkFile.close();

    log("✅ Successfully exported to: " + filename, 0);
    log("📊 File contains " + std::to_string(mesh.vertices.size()) + " vertices and "
        + std::to_string(mesh.triangles.size()) + " triangles", 0);

    return true;
}

} // namespace rmt
